### ISSUE TITLE
[Bug] Performance hit on Pleroma instance

### ISSUE THREAD

**Issue by pla1** [hyperspacedev/hyperspace#1]
Hi, 

When I startup Hyperspace it hits my Pleroma instance pla.social hard. CPU utilization goest 100%. Here is [the thread](https://pla.social/notice/9hPgFvvwPw0gawrH7I) I started about it. There is a [video](https://pla.social/media/b93863c4b74ed62c51b1fca8ea130cc9d510efbae41ad2c593e7fa6f944d11db.mp4?name=hyperspace.mp4) of the dev console that may give a clue as to what is happening. Let me know if I can provide any more data. 

Thanks, PLA

**Comment by alicerunsonfedora** [comment]
It appears ad if the rewrite of Hyperspace and the most recent betas have resolved this issue. I'm going to close this.
