### ISSUE TITLE
[Bug] Boosted/reblogged post menu has blue outline when focused in Chrome

### ISSUE THREAD

**Issue by travisk-codes** [hyperspacedev/hyperspace#108]
**Description**
Title mostly explains it. Chrome will place a blue outline around focused buttons. Because non-boosted posts do not have this outline, I assume it is unwanted behavior (and I personally find it unattractive)

**To Reproduce**
1. Open app in Chrome (version below)
2. Find a boosted post and click the "more" menu button
3. Should see menu items with the "focused" blue outline (see screenshot)

**Expected behavior**
Match styles of non-boosted post menu (no outline)

**Screenshots**
![Screenshot 2019-10-18 at 22 38 42](https://user-images.githubusercontent.com/7794722/67136993-8fe96100-f1fc-11e9-9482-24bd268ecbe0.png)

**App Information**
 - OS: Chrome OS version 77.0.3865.105
 - Browser: Chrome (help/about redirects to Chrome OS version when using Chrome on Chrome OS?)

**Additional Context**
I have a fix ready (basically just adding an "outline: none" style), but I hear it's good etiquette to submit an issue first :)

**Comment by tdkohlbeck** [comment]
worth noting that this bug does not show up in chrome on Android (and the menu is different as well?)

**Comment by alicerunsonfedora** [comment]
We'll take a look into this, though I'm unsure if this is an issue with our code or how Material-UI just handles things.
