### ISSUE TITLE
[Request] Characters limit is hardcoded

### ISSUE THREAD

**Issue by MasterGroosha** [hyperspacedev/hyperspace#125]
**Describe the bug**
It looks like app is hardcoded for 500 characters limit (as on flagship instance). However, this is not true for the Fediverse, since each instance can set any limit per toot.

**To Reproduce**
1. Create an account with instance limit of 501+ chars (f.ex. https://mastodon.ml)
2. Click on "Create toot"
3. Try creating post with 501 characters or more

**Expected behavior**
App should get characters limit from each instance separately. Currently you cannot create post with more than 500 chars no matter which limit it is.

**App Information (please complete the following information):**
 - OS: Linux
 - Version Hyperspace v1.0.3

**Comment by alicerunsonfedora** [comment]
We'll work on this and see what we can do. We hadn't found a way before to get the limit, but now it would be a matter of getting that data before reaching a request limit.

**Comment by alicerunsonfedora** [comment]
Also re-assigning as an enhancement request as this doesn't necessarily break the app.

**Comment by alicerunsonfedora** [comment]
Update: It appears that there is _not_ an official API endpoint to grab the maximum character limit, so we'll make a setting for this instead.

**Comment by alicerunsonfedora** [comment]
Should appear in v1.1.0-beta1, but here's what this would effectively look like in the Composer

![Screen Shot 2019-11-17 at 14 12 55](https://user-images.githubusercontent.com/13445064/69012486-7b57d000-0944-11ea-8aeb-2acf26312a8d.png)

**Comment by MasterGroosha** [comment]
Great, thank you!

**Comment by alicerunsonfedora** [comment]
Fixed with v1.1.0-beta1
