### ISSUE TITLE
[Request] Add Hyperspace to Brew

### ISSUE THREAD

**Issue by iero** [hyperspacedev/hyperspace#135]
As Hyperspace is not available in Mac App Store, you could make it available to Brew:
https://github.com/Homebrew/homebrew-cask
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by alicerunsonfedora** [comment]
We'll definitely take a look into it for the Desktop version. We are planning to also make a new version of Hyperspace dedicated to macOS/iOS that should be in the App Store at some point.

Noted as [HD-26]
