### ISSUE TITLE
Cannot go back

### ISSUE THREAD

**Issue by iero** [hyperspacedev/hyperspace#136]
When I click on "View profile" or "View Thread", how can I go back to the previous screen?

![Shot 2019-12-07 at 13 46 13](https://user-images.githubusercontent.com/2870245/70380990-2f22fe80-18f8-11ea-8064-d8cb0d28e93a.jpg)

There are no "Go back" icon?

**Comment by alicerunsonfedora** [comment]
There's a keyboard shortcut you can use, `⌘+[`, or you can go to **View** &rsaquo; **Back**.

**Comment by iero** [comment]
It's not very convenient on AZERTY keyboard.. you need to push 4 keys to do this action: cmd+optio+shift+(

Could you make it more accessible with trackpad ? Ie: two fingers from left to right 
Or at least one small "back" floating button..

**Comment by alicerunsonfedora** [comment]
Request for a back button has been noted in our issue tracker ([HD-28]). This should probably release in v1.1.0-beta2.
