### ISSUE TITLE
[Bug] Delay in rendering profile header on Settings page

### ISSUE THREAD

**Issue by travisk-codes** [hyperspacedev/hyperspace#142]
**Describe the bug**

When navigating to the settings page, or changing a setting, there is a brief delay before the header renders, which makes the buttons change location on the page. This can be annoying if trying to select a button before the render.

**To Reproduce**
1. Go to settings page?

**Expected behavior**

I expect the layout to remain static, even if the header is not yet loaded.

**App Information:**

- Latest (mobile) Chrome

**Additional context**

I'm trying to fix this issue, but not sure what's the best course of action. In `componentDidMount`, it GETs `/accounts/verify_credentials` and sets the response as `state.currentUser`, otherwise getting account data from local storage. I assume the delay is between page load and the GET request? The `render` method has `this.state.currentUser ? <[header]> : null`.

I've tried:
- loading `Account` from `localStorage` before the GET, but this doesn't seem to work (tried placing it in `componentDidMount`, `componentWillMount`, and `constructor`)
- replacing `null` with a dummy header, but the header height seems to be set after render (`pageHeroBackground: { height: 'intrinsic' }`)? As a side note, Chrome DevTools says that 'intrinsic' is an invalid value.

Would love some direction on how to tackle this. <3

**Comment by alicerunsonfedora** [comment]
This usually happens because the app is gathering the account data for said header.
