### ISSUE TITLE
Adopt a masonry layout on wider screens for the user profile and the search page

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#150]
As #56 is implemented, seems it makes sense to adopt the same layout for other similar pages that otherwise have a lot of unused space:

- user profile
- search page

**Comment by alicerunsonfedora** [comment]
Marked in our tracker for `v1.1.0-beta3` as [HD-36]

**Comment by travisk-codes** [comment]
sounds good, I'll get to it in the next few days if I'm not beaten to the
punch
