### ISSUE TITLE
[Bug] Wrong redirect after login on subdirectory

### ISSUE THREAD

**Issue by allo-** [hyperspacedev/hyperspace#152]
**Describe the bug**
Hyperspace redirects after login  (with a code) in the web version to "/#" instead to its full location (e.g. "/hyperspace/")

**To Reproduce**
1. Login using a Code
2. Authorize the App
3. Use the code to login at hyperspace

**Expected behavior**
You are redirected to the hyperspace start page

** Actual behavior**
You are redirected to "/#"

**App Information (please complete the following information):**
 - Browser: Firefox

**Additional context**
I am using the static release 1.0.4

**Comment by alicerunsonfedora** [comment]
Noted in [HD-38] and marked for v1.1.0-beta3

**Comment by alicerunsonfedora** [comment]
Could you tell me how your Hyperspace installation is configured? I'm unsure of what is the exact cause, though it does appear that we do redirect to "/#" intentionally. I'm guessing that there's an issue with the window location, but I want to make sure this isn't just a directory issue.

From `Welcome.tsx`:
```typescript
window.location.href =
    window.location.protocol === "hyperspace:"
    ? "hyperspace://hyperspace/app/"
    : `https://${window.location.host}/#/`;
```

**Comment by allo-** [comment]
I have set `location	"https://host/hyperspace/"`.

And I think your code snippet always redirects to `https://host/` and discards the path after the hostname. I am not sure if there is a reason for redirecting to `/`, but on my host hyperspace is only available at `/hyperspace/`, so it seems that it is either not the right redirect, or you (currently) cannot install hyperspace in a subfolder.

**Comment by alicerunsonfedora** [comment]
That is true and makes sense as to where the issue is coming from. Currently, Hyperspace doesn't support being installed on a subdirectory at the moment, but should appear in a beta version of v1.1.

**Comment by allo-** [comment]
Ah, okay. It almost worked ;-).
I now moved it to an own subdomain and it works fine.

Because it is already planned for a new version, I close this bug now.

**Comment by alicerunsonfedora** [comment]
Re-opening so we can keep track of this

**Comment by alicerunsonfedora** [comment]
Whoops, that backfired. Re-opening as the PR is still open
