### ISSUE TITLE
[Bug] Account names don't display emoji properly

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#154]
Users that have HTML markup in their names appear with the HTML unrendered, which is definitely not the way that is expected.

**To Reproduce**
1. Subscribe to an account such as `archlinux@pokemon.men`
2. Open it in Hyperspace
3. Compare how it's rendered in the Mastodon UI

**Expected behaviour**
An account name should be rendered much prettier than having HTML unrendered. I believe HTML should be either stripped away or rendered in a safe manner somehow (or just unsafely as Mastodon does I suppose).

**Screenshots**
See the screenshot how it looks - https://pasteboard.co/IQeT0tB.png
The same account in the original Mastodon UI - https://pasteboard.co/IQeUgf0.png

**App Information:**
Hyperspace 1.1.0 Dev Channel

**Comment by alicerunsonfedora** [comment]
Appears to be a stripping HTML issue. Marked as [HD-39] in internal and set for epic v1.1.0-beta3.

**Comment by alicerunsonfedora** [comment]
It turns out this bug was an issue with the way #144 was implemented and that it didn't pass on `dangerouslySetInnerHTML`, meaning emojis wouldn't be displayed properly. Renaming the bug and waiting for a fix with #155

**Comment by alicerunsonfedora** [comment]
I'll also assign you to the PR then, @travisk-codes
