### ISSUE TITLE
[Bug] GIFV videos/images are not displaying in Chrome, Firefox

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#157]
Seems videos are not rendered properly, compare this -
https://hyperspaceapp-next.herokuapp.com/#/conversation/103517207102612516
and the original post - 
https://framapiaf.org/users/nautilus/statuses/103517206996147654

**Comment by alicerunsonfedora** [comment]
I don't see a video on this post as it appears to be a GIF.

**Comment by pioneer** [comment]
Yes, it's shown as a GIF on the original post, but the actual link is https://framapiaf.s3.framasoft.org/framapiaf/media_attachments/files/006/177/513/original/00cd39d17acffa98.mp4, so that's why I call it a video.

**Comment by alicerunsonfedora** [comment]
After some other investigations, we've discovered that the issue in question appears to be a problem where other browsers aside from Safari aren't able to display or view files in the GIFV format. Going to rename the issue as such.
