### ISSUE TITLE
[Request] Add support for playing media (ie audio files)

### ISSUE THREAD

**Issue by LadyFuzztail** [hyperspacedev/hyperspace#158]
See : https://awoo.space/users/FreyaManibrandr/statuses/103519395487681147

This is what it looks like in Hyperspace :
![image](https://user-images.githubusercontent.com/8291991/72775410-39e7e780-3c49-11ea-9cb5-42817826bf94.png)

What it looks like is that it still thinks that it's an image/gallery, but because there's no image data, it just displays the controls for navigating the gallery, but no image.

**Comment by alicerunsonfedora** [comment]
We currently have this already implemented in the beta versions of Hyperspace v1.1.0 and should make its way to the stable release in a few months (#121). 

You can try the beta online here: https://hyperspaceapp-next.herokuapp.com
