### ISSUE TITLE
[Bug] Corrupted images display

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#159]
This seems to be a federation bug that should be submitted to upstream as well.

Compare this profile on mastodon.social https://mastodon.social/web/accounts/886063
and
the original profile https://mastodon.ml/@SiberiaBreadFactory

The original profile has a proper profile picture, whereas the mastodon.social one has a corrupted image. So it comes corrupted to Hyperspace as well https://hyperspaceapp-next.herokuapp.com/#/profile/886063

I'm not seeing the Mastodon API returns the original image URL (correct me if I'm wrong), so looks like fetching the original image requires tricky things. But clearly the Mastodon UI displays such images a little bit nicer, so maybe a placeholder is worth to show instead of such images.

**Comment by alicerunsonfedora** [comment]
What you're describing might be an issue with the Mastodon API or something upstream. We do try to get the respective image, starting with the avatar, and then the static avatar as a fallback. Given that both of these error on the server's end and not necessarily Hyperspace, I don't think there's anything we can do at the moment. I recommend submitting an issue report upstream to Mastodon and see if there's a fix there. If there are any changes to the API that we need to make on our end, we'll do so.

For now, this appears to be an upstream issue and not Hyperspace-specific, so I'm marking it as such and closing, though I will keep an eye out on it.

**Comment by pioneer** [comment]
I've just tested this simple snippet, and it works just fine with corrupted images from Mastodon (I've put a random placeholder image found in Google into the `onerror` hanlder).
```
<img src="https://files.mastodon.social/accounts/avatars/000/872/604/original/1133bd23928809c8.jpeg"
onerror='this.src="https://ya-webdesign.com/transparent250_/no-image-png.png"'
/>
```
Having such images appear quite regularly in my feed, for example see the Barret's avatar on the screenshot in https://github.com/hyperspacedev/hyperspace/issues/163, can we just replace such images with a proper placeholder for now?

**Comment by pioneer** [comment]
Submitted to the upstream https://github.com/tootsuite/mastodon/issues/12925

**Comment by alicerunsonfedora** [comment]
As it appears this was an issue with mastodon.social and not Hyperspace itself, going to close this issue now.
