### ISSUE TITLE
[Improvement] Confusing "Follow account" button in the Notifications for already followed accounts

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#162]
The "Follow account" button in the notifications appears after a follow despite I have followed the account back or not, see the screenshot
![Выделение_020](https://user-images.githubusercontent.com/200538/72895416-eeefd200-3d25-11ea-8947-2ed07b8e5b5b.png)

It's a bit confusing to have a follow button for already followed accounts, so UX-wise, maybe worth either removing it or replacing with an unfollow button?

**Comment by alicerunsonfedora** [comment]
We'll consider it, but we've recently implemented a bug fix to prevent infinite follows (i.e., multiple follow requests) for that button.
