### ISSUE TITLE
[Bug] New post also saves post as draft

### ISSUE THREAD

**Issue by travisk-codes** [hyperspacedev/hyperspace#166]
**Describe the bug**
If I submit a new toot, that same toot is saved as a draft

**To Reproduce**
1. toot a new toot
2. Draft snackbar should trigger
3. Open new toot modal, click to see draft

**Comment by alicerunsonfedora** [comment]
Should be a simple check in the `componentWillUnmount` that will resolve it. Will handle it tomorrow morning 👍
