### ISSUE TITLE
Help - Hyperspace Documents

### ISSUE THREAD

**Issue by imattau** [hyperspacedev/hyperspace#181]
**Describe the bug**
Link to Hyperspace Desktop Docs result in a 404 error on the webpage

**To Reproduce**
1. Go to Help
2. Click on Hyperspace Desktop Docs

**Expected behavior**
Link to documentation web page

**App Information (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser Brave

**Comment by alicerunsonfedora** [comment]
This appears to be more of an issue with our site's setup than Hyperspace Desktop itself (but important to note). Closing this issue and making the necessary changes on the Hyperspace website (hyperspacedev/hyperspacedev.github.io).
