### ISSUE TITLE
[Bug] Welcome Page Link gives a 404

### ISSUE THREAD

**Issue by 2br-2b** [hyperspacedev/hyperspace#187]
Hello!

On the welcome page, the link `full username` brings you to [https://docs.joinmastodon.org/usage/decentralization/#addressing-people](https://docs.joinmastodon.org/usage/decentralization/#addressing-people); however, the link brings you to a 404 error.

![image](https://user-images.githubusercontent.com/43968991/77791250-4a935000-7034-11ea-909b-a94733bfb774.png)

**Comment by alicerunsonfedora** [comment]
The Mastodon documentation was redesigned recently, so this would explain the 404 problem. We'll point to the new one at https://docs.joinmastodon.org/user/signup/#address in the upcoming beta for v1.1.0
