### ISSUE TITLE
[Bug] Avatar in App header, on change, requires refresh to show new avatar

### ISSUE THREAD

**Issue by travisk-codes** [hyperspacedev/hyperspace#194]
**Describe the bug**
If you change your avatar, it appears to update (without refresh) everywhere except for the header, which updates upon refresh. 

**To Reproduce**
1. Edit profile
2. Change avatar
3. Witness updates on Edit Profile page header, Profile Page header and posts
4. Witness lack-of-update in App header

**Expected behavior**
The App Header to update along with everything else

**Screenshots**
![image](https://user-images.githubusercontent.com/7794722/79051657-515abf00-7bff-11ea-99d7-84fd0f1f6754.png)

**App Information (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Additional context**
Minor, low-pri

**Comment by alicerunsonfedora** [comment]
Probably a local storage issue, if I were to guess. It doesn’t necessarily pick up changes to it immediately and often requires a refresh

**Comment by travisk-codes** [comment]
Looks like all other avatar locations are loaded on `didMount` (update makes sense when navigating to a new page) or are updated via `setState`, which makes sense for the immediate update on `You.tsx`. Does it make sense to lift state up into `AppLayout`? Doesn't seem like the correct concern. are `localStorage` updates made everywhere immediately?

**Comment by alicerunsonfedora** [comment]
I don't think `localStorage` loads immediately, hence why some places require that we refresh the browser. It's also a bit tricky tying `AppLayout` with the pages since they're in separate locations, in addition to it being "higher" up in the tree.

**Comment by travisk-codes** [comment]
Do you think account info would be a good use case for React context?

**Comment by alicerunsonfedora** [comment]
Perhaps. I'm a little unfamiliar with it, but it's worth a try.
