### ISSUE TITLE
[Bug] Header avatar menu does not close on click

### ISSUE THREAD

**Issue by travisk-codes** [hyperspacedev/hyperspace#197]
**Describe the bug**
When you open the Header menu (avatar button) and select Profile, Edit Profile, or Manage follow requests, the menu does not close upon selection

**To Reproduce**
1. Open menu
2. Click one of the first three options
3. Witness behavior

**Expected behavior**
I would expect the menu to close upon selection.

**App Information (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Desktop Firefox (Developer Version)

**Additional context**
Feel free to argue in favor of the current behavior.

**Comment by alicerunsonfedora** [comment]
Yup, that's a bug that needs to be fixed. I think the way Material-UI handles menus is a bit weird, and I think that behavior of it closing upon selection is expected.
