### ISSUE TITLE
[Bug] "Notification" is not defined

### ISSUE THREAD

**Issue by bleonard252** [hyperspacedev/hyperspace#206]
**Describe the bug**
Upon clicking Settings, the page blanks and the browser console reports ReferenceError: "Notification is not defined". Clicking the first link in the trace shows me transpiled code that indicates that it has something to do with push notifications (which is on, and my browser supports).

**To Reproduce**
1. Sign in (Pleroma?)
2. Click "Settings" in the drawer
3. Open browser console

**Expected behavior**
The settings screen should show.

**Screenshots**
N/A (white page)

**App Information (please complete the following information):**
 - OS: Debian amd64
 - Browser: Firefox Beta
 - Version: 77

**Additional context**
It still occurs with privacy.resistFingerprinting off (which I thought would make it work). I don't know what's trying to get Notification (permission check/request?).

**Comment by alicerunsonfedora** [comment]
Notes from Riot conversation:

- `"Notification" in window` returned false
- Possible context: edge case where notifications that aren't supported are being treated as supported
