### ISSUE TITLE
Arch Linux package needs maintainer (hyperspace-bin)

### ISSUE THREAD

**Issue by ariasuni** [hyperspacedev/hyperspace#218]
I’m maintaining the [package `hyperspace-bin` on the AUR](https://aur.archlinux.org/packages/hyperspace-bin/) for some time now, but I’ll stop updating it because I have other priorities. The package can easily be claimed and updated by another Arch Linux user.

**Comment by alicerunsonfedora** [comment]
Thanks for the update. We'll pin this issue to see if anyone else wants to maintain this package for Arch Linux.

As a note to Arch Linux users, we also offer packages via the AppImage and Snap formats, and we are looking into bringing Hyperspace Desktop to Flatpak via Flathub (see #220). You can also access Hyperspace Desktop at https://hyperspaceapp.herokuapp.com.

**Comment by travisk-codes** [comment]
I use arch--what would be the process for switching maintainers?

**Comment by ariasuni** [comment]
You need to create an account on [AUR](https://aur.archlinux.org) and on the [`hyperspace-bin`](https://aur.archlinux.org/packages/hyperspace-bin/) page, in the left sidebar “Package Actions”, choose “Adopt package”.

Then, you will need to maintain the [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) and [submit new versions to the AUR](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Publishing_new_package_content).

**Comment by alicerunsonfedora** [comment]
The AUR repo has been updated to the latest desktop release thanks to karmanyaahm. I'll close this for now until we need to raise this issue again.
