### ISSUE TITLE
Hyperspace is dead?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [hyperspacedev/hyperspace#248]
The last version was Hyperspace Desktop v1.1.4 on 3 Oct 2020.

Any update? Is dead this repo ?

**Comment by alicerunsonfedora** [comment]
We've described the current state of Hyperspace Desktop at https://github.com/hyperspacedev/hyperspace/discussions/244.

**Comment by AnonymousWebHacker** [comment]
I'm sorry, I had read it on the site's blog, your last article.

The client for macos is very good

**Comment by alicerunsonfedora** [comment]
> I'm sorry, I had read it on the site's blog, your last article.
> 
> 
> 
> The client for macos is very good

No worries. The Desktop client may appear dead right now because development has stalled, but I can assure you we're just as interested to keep it alive since it offers a good experience on both Windows and Linux while we focus on building a great native experience for iOS/iPadOS and macOS.
