### ISSUE TITLE
[Question] Can Hyperspace more as one account ?

### ISSUE THREAD

**Issue by BogusCurry** [hyperspacedev/hyperspace#36]
Hi there ;D
I testet your program and has a little question, can hyperspace more as one account ?

Greetings
Bogus

**Comment by alicerunsonfedora** [comment]
@BogusCurry Currently, the latest betas of Hyperspace 1.0 doesn't truly support multi-accounts, though it is planned in our roadmap at some point. (Some of our code even references this option, though it's hidden at the time being)

For now, you could make use of browser containers, private windows, etc. to sign in to Hyperspace with different accounts.

**Comment by alicerunsonfedora** [comment]
Also, I just filed the issue officially so it appears on the roadmap: #37
