### ISSUE TITLE
[question] second login mastodon actived again

### ISSUE THREAD

**Issue by BogusCurry** [hyperspacedev/hyperspace#38]
Hello again ;D
When I logout, then I log in, I must actived my mastodon account actived again. Why that ?

Greetings
Bogus

**Comment by alicerunsonfedora** [comment]
Hi,

When you log out, you are essentially removing your access token and other essential components needed to login to the app.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/13445064/56918537-4e1d0080-6a8c-11e9-9465-05c56c3a6d5a.png">

As you cannot log back in with the same access token, you have to complete the authorization process again.
