### ISSUE TITLE
[Request] Adopt a masonry layout on wider screens

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/hyperspace#56]
Currently, Hyperspace forces a one-column view of posts that scales across devices. However, it might be better to implement something that can fold out into a grid of posts like Google+ did (masonry layout):

![Google+ homepage](https://cdn-images-1.medium.com/max/2400/1*PwaWyyPwlrN6dEO5QVvEfw.png)
> Image from Wiktor Olejniczak's [_Design Overview — Google+_](https://medium.com/@myfrom/design-overview-google-829121491a)

- credit to Azazer via email for this request

## Possible challenges

- Computation of post sizes in grid might slow down app
- Existing NPM packages might not have TypeScript/Material-UI support
- `<Grid>` element in Material-UI is _not_ masonry-responsive

**Comment by pioneer** [comment]
Could it be also implemented on the user feed and search pages?
