### ISSUE TITLE
AppImage and snap sandboxes not configured

### ISSUE THREAD

**Issue by shouko-git** [hyperspacedev/hyperspace#67]
When I try to execute appimage on Manjaro I am presented with this console output
`[5591:0619/213110.898717:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_HypersgkUaW5/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)`

**Comment by alicerunsonfedora** [comment]
Hmm, never had this issue before. I'm unfortunately unable to really test the since I use a Mac for most development, but we'll take a look into it and see if it's a build configuration issue.

**Comment by blucoat** [comment]
I have the same issue after running the `1.0.0-beta5` snap on ubuntu 18.04:

```
[1332:0715/194355.734988:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/hyperspace/6/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by alicerunsonfedora** [comment]
We'll see if 1.0.0beta6 inherently fixes this since we're shipping with updated dependencies.

**Comment by alicerunsonfedora** [comment]
As of 1.0.0beta7, it appears that the sandboxes are in place just fine and that there are no errors from it. But, I am noticing other errors relating to Buffer. Since Buffer is somewhat unrelated to this sandboxing, I'll mark this as complete.
