### ISSUE TITLE
About page blanks in Pleroma instances

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/hyperspace#69]
Initially from #65 . Details as follows from @bleonard252:

> My Pleroma instance seems to run very well on Hyperspace. The number one bug I'm running into is the About page-- it flashes a "Loading" screen then the whole page blanks. The Firefox Inspector shows an empty div.root element.

**Comment by bleonard252** [comment]
Found the cause of the issue:
<details><summary>The area in the code where this error occurred</summary>

```jsx
<ListItem>
    <ListItemAvatar>
        <LinkableAvatar to={`/profile/${this.state.instance? this.state.instance.contact_account.id: 0}`} alt="Instance admin" src={this.state.instance? this.state.instance.contact_account.avatar_static: ""}/>
    </ListItemAvatar>
    <ListItemText primary="Instance admin" secondary={
        this.state.instance ? `${this.state.instance.contact_account.display_name} (@${this.state.instance.contact_account.acct})`:
        "Loading..."
    }/>
    <ListItemSecondaryAction>
        <Tooltip title="Send a post or message">
            <LinkableIconButton to={`/compose?visibility=public&acct=${this.state.instance? this.state.instance.contact_account.acct: ""}`}>
                <ChatIcon/>
            </LinkableIconButton>
        </Tooltip>
        <Tooltip title="View profile">
            <LinkableIconButton to={`/profile/${this.state.instance? this.state.instance.contact_account.id: 0}`}>
                <AssignmentIndIcon/>
            </LinkableIconButton>
        </Tooltip>
    </ListItemSecondaryAction>
</ListItem>
```

</details>

This appears to have happened because Pleroma doesn't have a `instance.contact_account`. So, to mitigate the problem, I removed that item on Pleroma instances by wrapping it in a big not-Pleroma check:

```jsx
{(localStorage['isPleroma'] == "false") && <ListItem>
...
</ListItem>}
```

PR coming soon (see #65).

**Comment by alicerunsonfedora** [comment]
Sounds good @bleonard252 , and thanks for catching the error! If you can, could you add your PR to the `beta6` branch?

**Comment by bleonard252** [comment]
Will do! I can't test it on my instance right now because I broke it trying to update it. As soon as I can make sure it's all working, I'll do that.
