### ISSUE TITLE
"build-desktop" command appears not to exist

### ISSUE THREAD

**Issue by jdkruzr** [hyperspacedev/hyperspace#76]
Instructions tell you "build-desktop" should create a deployable .deb of the application. I tried `build-desktop`, `npm build-desktop` and `npm build desktop` and none of those work.
```
jtd@Volans:~/hyperspace$ npm version
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
{ hyperspace: '1.0.0-beta5',
  npm: '5.8.0',
  ares: '1.14.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.36.0',
  node: '10.15.2',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.24.1',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }
jtd@Volans:~/hyperspace$ npm --version
5.8.0
```
```
jtd@Volans:~/hyperspace$ nodejs --version
v10.15.2
```

**Comment by alicerunsonfedora** [comment]
Could you provide the logs for when you attempt to run `npm run build-desktop`?

**Comment by alicerunsonfedora** [comment]
This issue hasn't been updated in a while. From my understanding, it appears that you're trying to run the `build-desktop` command like it's a standard nom command. `build-desktop` is a command that needs to be run via `npm run` and not just `npm`.

To reiterate:
```
npm run build-desktop
```

If this doesn't work and something occurs, feel free to comment. For now, I'm going to close out this issue.
