### ISSUE TITLE
[Linux deb] shows at the top «Careful: you’re running in developer mode.»

### ISSUE THREAD

**Issue by ariasuni** [hyperspacedev/hyperspace#80]
When using the release asset [hyperspace_1.0.0-beta5_amd64.deb](https://github.com/hyperspacedev/hyperspace/releases/download/1.0.0beta5/hyperspace_1.0.0-beta5_amd64.deb), I’m getting a warning at the top of the window that I’m running the app in developer mode.

**Comment by alicerunsonfedora** [comment]
This is intended as Hyperspace 1.x is currently in beta.

**Comment by ariasuni** [comment]
OK, but the way it is phrased make it look like a mistake. Maybe it could be written more explicitly that it is in beta, rather than speaking about some developer mode?

**Comment by alicerunsonfedora** [comment]
It is not a mistake as this is intended behavior. We may consider "rewording" it, but the functionality and message seems to be working as intended.

**Comment by ariasuni** [comment]
Nice, thanks!
