### ISSUE TITLE
Re-review licensing

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/hyperspace#87]
This issues falls in-tandem with #71 and #86.

As per a suggestion from /dev/ponies@ponies.im:

> @alicerunsonfedora as you've got a rather small number of contributors, please consider switching to @thufie's NPL license so that gab users can't just fork it and use it for hate anyway without being in violation of the license
> 
> consider her CNPL license as well, it includes additional restrictions on hierarchical commercial usage

If we merge these changes, we'll need to update our license. We need to keep in mind of the following things:

- The OSS license should still give us the proper permissions to submit apps to the Mac App Store (licenses like GPL are MAS-incompatible).
- The license should also fall in line with the aforementioned suggestion so that Hyperspace isn't misused or re-written to be misused.

**Comment by Bio-ico** [comment]
Concept: write a eula that specifically mentions that users agree not to remove the blocks against gab, and if they do they are liable to whatever punishments or at the very least get their stuff taken down.

**Comment by alicerunsonfedora** [comment]
After a discussion, we have determined that all future versions of Hyperspace will be licensed under the NPL. Expect a pull request to master that puts this into effect.
